title: Welcome to anonymous_Eune
description: Flexton is a responsive and ultra-minimal theme for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hhyyee1109.github.io"

# Author
author-name:    익명의 은혜
author-image:   sense.jpg
author-job:     초보 기획자 겸 프리랜서 에디터
author-email:   your-email@domain.com # Add your email for contant form.
author-careerly:   your-email@domain.com
author-branch:   your-email@domain.com
#author-twitter: artemsheludko_ # Add your twitter account
about-author:   문예창작학과 출신의 초보 기획자. 아무 말이나 합니다. 
brunch.co.kr@ 
careerly.co.kr/profiles/223518

# Social settings
social-twitter:   artemsheludko_
social-facebook:
social-github:    artemsheludko
social-pinterest: artemsheludko
social-instagram: artemsheludko_
social-youtube:
social-vk: artemsheludko_   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
